# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mezzanine.core.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordertable', '0002_auto_20180227_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Регион')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MasterReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateField(default=django.utils.timezone.now)),
                ('mastery', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1, verbose_name='Мастерство')),
                ('punctuality', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1, verbose_name='Пунктуальность')),
                ('responsibility', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1, verbose_name='Ответственность')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('text_review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='ordertable.OrderTableItem', verbose_name='Работа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы о мастерах',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Регион')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_count', models.IntegerField(default=0, editable=False)),
                ('rating_sum', models.IntegerField(default=0, editable=False)),
                ('rating_average', models.FloatField(default=0, editable=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('image', mezzanine.core.fields.FileField(default='', help_text='Загрузите Ваше изображение.', max_length=255, verbose_name='Ваше изображение')),
                ('background', mezzanine.core.fields.FileField(default='', help_text='Загрузите обложку профиля.', max_length=255, verbose_name='Обложка профиля')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('allow_blogpost_count', models.PositiveIntegerField(default=10, verbose_name='Разрешенное количество записей в Блоге')),
                ('allow_product_count', models.PositiveIntegerField(default=10, verbose_name='Разрешенное количество товаров в магазине')),
                ('allow_ordertable_count', models.PositiveIntegerField(default=10, verbose_name='Разрешенное количество заявок для Стола заказов')),
                ('status', models.IntegerField(choices=[(0, 'Покупатель'), (1, 'Мастер')], default=0, help_text='Будучи мастером вы сможете получать персональные заказ', verbose_name='Тип профиля')),
                ('bio', mezzanine.core.fields.RichTextField(blank=True, default='', verbose_name='О себе')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='profiles.City', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Country', verbose_name='Страна')),
                ('region', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='profiles.Region', verbose_name='Регион')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Region'),
        ),
    ]
