# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-20 17:09
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=mezzanine.core.fields.FileField(default='', help_text='Загрузите Вашу фотографию.', max_length=255, verbose_name='Ваше изображение'),
        ),
    ]
