# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180220_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_average',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_sum',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=mezzanine.core.fields.FileField(default='', max_length=255, verbose_name='Ваше изображение'),
        ),
    ]
