# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-21 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180221_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_sum',
        ),
    ]
