# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_masterreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='masterreview',
            name='text_review',
            field=models.TextField(default='tmp', verbose_name='Отзыв'),
            preserve_default=False,
        ),
    ]
