# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180424_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_sum',
        ),
        migrations.AlterField(
            model_name='masterreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
