# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180221_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
