# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-21 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comments_count',
        ),
    ]
