# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180510_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterreview',
            name='master',
        ),
        migrations.RemoveField(
            model_name='masterreview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='masterreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='MasterReview',
        ),
    ]
