# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordertable', '0006_auto_20180517_1942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_auto_20180518_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mastery', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Мастерство')),
                ('punctuality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Пунктуальность')),
                ('responsibility', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Ответственность')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('text_review', models.TextField(verbose_name='Отзыв')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='ordertable.OrderTableItem', verbose_name='Работа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы о мастерах',
            },
        ),
    ]
