# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-07 13:03
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180222_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=mezzanine.core.fields.FileField(default='', help_text='Загрузите обложку профиля.', max_length=255, verbose_name='Обложка профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=mezzanine.core.fields.FileField(default='', help_text='Загрузите Ваше изображение.', max_length=255, verbose_name='Ваше изображение'),
        ),
    ]
