# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-07 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180307_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_ordertable_count',
            field=models.PositiveIntegerField(default=10, verbose_name='Разрешенное количество заявок для Стола заказов'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='condition',
            field=models.CharField(choices=[(0, 'Покупатель'), (1, 'Мастер')], default=0, help_text='Готовая работа - работа уже ждет покупателя. Под заказ - Вы можете выполнить точно такую же работу, но потребуется некоторое время. Для примера - повторить работу точь-в-точь невозможно.', max_length=255, verbose_name='Состояние'),
        ),
    ]
