# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_masterreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterreview',
            options={'verbose_name': 'Отзыв о мастере', 'verbose_name_plural': 'Отзывы о мастерах'},
        ),
        migrations.RenameField(
            model_name='masterreview',
            old_name='text_review',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='masterreview',
            name='user',
        ),
        migrations.AddField(
            model_name='masterreview',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='author_master_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='ordertable.OrderTableItem', verbose_name='Работа'),
        ),
    ]
