# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180518_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreview',
            name='mastery',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Мастерство'),
        ),
        migrations.AlterField(
            model_name='masterreview',
            name='punctuality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Пунктуальность'),
        ),
        migrations.AlterField(
            model_name='masterreview',
            name='responsibility',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Ответственность'),
        ),
    ]
