# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180519_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterreview',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
