# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShopDeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserShopDelivery')),
            ],
            options={
                'verbose_name': 'Способ доставки магазина',
                'verbose_name_plural': 'Способы доставки магазина',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Обработанный'), (3, 'Отправленный'), (4, 'Завершенный'), (5, 'Отмененный')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='delivery_options',
            field=models.ManyToManyField(through='shops.UserShopDeliveryOption', to='shops.UserShopDelivery'),
        ),
        migrations.AddField(
            model_name='usershopdeliveryoption',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserShop'),
        ),
    ]
