# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-19 14:41
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_usershop_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='background',
            field=mezzanine.core.fields.FileField(default='', help_text='Загрузите обложку магазина.', max_length=255, verbose_name='Обложка магазина'),
        ),
    ]
