# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-19 14:51
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180219_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershop',
            name='file',
        ),
        migrations.AlterField(
            model_name='usershop',
            name='image',
            field=mezzanine.core.fields.FileField(default='', help_text='Загрузите логотип магазина.', max_length=255, verbose_name='Обложка магазина'),
        ),
    ]
