# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180516_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='condition',
            field=models.CharField(choices=[(1, 'Готовая работа'), (2, 'Под заказ'), (3, 'Для примера')], default=1, help_text='Готовая работа - работа уже ждет покупателя. Под заказ - Вы можете выполнить точно такую же работу, но потребуется некоторое время. Для примера - повторить работу точь-в-точь невозможно.', max_length=15, verbose_name='Состояние'),
        ),
    ]
