# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-21 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20180219_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershop',
            name='comments_count',
        ),
    ]
