# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_usershop_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='condition',
            field=models.CharField(choices=[('В наличии', 'in stock'), ('Под заказ', 'Под заказ'), ('Для примера', 'Для примера')], default='В наличии', max_length=255, verbose_name='Состояние'),
        ),
    ]
