# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20180225_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='condition',
            field=models.CharField(choices=[('finish', 'Готовая работа'), ('pre_order', 'Под заказ'), ('for_example', 'Для примера')], default='finish', help_text='Удалить поле', max_length=255, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='pre_order',
            field=models.BooleanField(default=False, help_text='Удалить поле', verbose_name='Для примера'),
        ),
    ]
