# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20180225_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Разместить работу можно только в одной категории.', to='shop.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='condition',
            field=models.CharField(choices=[('finish', 'Готовая работа'), ('pre_order', 'Под заказ'), ('for_example', 'Для примера')], default='finish', help_text='Готовая работа - работа уже ждет покупателя. Под заказ - Вы можете выполнить точно такую же работу, но потребуется некоторое время. Для примера - повторить работу точь-в-точь невозможно.', max_length=255, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='pre_order',
            field=models.BooleanField(default=False, help_text='Удалить поле', verbose_name='Удалить'),
        ),
    ]
