# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-17 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_remove_shopproduct_pre_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='size',
            field=models.CharField(blank=True, default='', help_text='Укажите размеры товара', max_length=255, verbose_name='Размер'),
        ),
    ]
