# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_updated',
            field=models.DateTimeField(null=True, verbose_name='Last updated'),
        ),
    ]
