# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_cart_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='id'),
        ),
    ]
