# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0011_auto_20180227_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='true_product_id'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='true_product_id'),
        ),
    ]
