# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20180518_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='rating_average',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='rating_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='rating_sum',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
