# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20180227_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
