# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20180228_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shop_id',
            field=models.IntegerField(default=0, verbose_name='shop_id'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shop_image',
            field=models.IntegerField(default=0, verbose_name='shop_id'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop_id',
            field=models.IntegerField(default=0, verbose_name='shop_id'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop_image',
            field=models.IntegerField(default=0, verbose_name='shop_id'),
        ),
    ]
