# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20180518_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='rating_sum',
        ),
    ]
