# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20180518_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='comments_average',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='comments_sum',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
