# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_auto_20180518_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='comments_average',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='comments_sum',
        ),
    ]
