# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_auto_20180301_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_cart', to='shops.ShopProduct'),
            preserve_default=False,
        ),
    ]
