# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 15:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0017_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 15, 28, 44, 433142, tzinfo=utc))),
                ('mastery', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Мастерство')),
                ('punctuality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Пунктуальность')),
                ('responsibility', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Ответственность')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name_plural': 'Отзывы о товарах',
                'verbose_name': 'Отзыв о товаре',
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
