# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='main_image',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='Изображение'),
        ),
    ]
