# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_shopproduct_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='main_image',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Изображение'),
        ),
    ]
