# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_auto_20180302_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Все заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='item_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(default='', max_length=255, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.UserShop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In proccess'), (3, 'Closed'), (4, 'Canceled')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_additional_info',
            field=models.TextField(blank=True, verbose_name='Ваши пожелания по заказку'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_adress',
            field=models.CharField(default=1, max_length=255, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_city',
            field=models.CharField(default=1, max_length=100, verbose_name='City/Suburb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_country',
            field=models.CharField(default=1, max_length=100, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_postcode',
            field=models.CharField(default=1, max_length=15, verbose_name='Zip/Postcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_region',
            field=models.CharField(default=1, max_length=100, verbose_name='State/Region'),
            preserve_default=False,
        ),
    ]
