# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20180302_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Завершен'), (4, 'Отменен')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
    ]
