# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20180518_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='shops.ShopProduct', verbose_name='Товар'),
        ),
    ]
