# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0021_auto_20180518_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set([('author', 'product')]),
        ),
    ]
