# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_auto_20180518_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
    ]
