# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_order_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_adress',
            field=models.CharField(blank=True, help_text='Улица, дом, подъезд, квартира', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_postcode',
            field=models.CharField(blank=True, max_length=15, verbose_name='Zip/Postcode'),
        ),
    ]
