# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0024_auto_20180302_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_total',
            new_name='price_total',
        ),
    ]
