# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0025_auto_20180302_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_orders', to='shops.ShopProduct'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_additional_info',
            field=models.TextField(blank=True, verbose_name='Пожелания по заказку'),
        ),
    ]
