# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0025_auto_20180519_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershop',
            name='reviews_average',
        ),
        migrations.RemoveField(
            model_name='usershop',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='usershop',
            name='reviews_sum',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reviews_average',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reviews_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reviews_sum',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
