# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0026_auto_20180519_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='reviews_average',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
