# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0026_auto_20180302_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shop_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shop_slug',
        ),
    ]
