# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0027_auto_20180302_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_total',
            new_name='item_total',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего'),
        ),
    ]
