# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0028_auto_20180520_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_from_session',
            field=models.BooleanField(default=True, verbose_name='Корзина находится в сессии?'),
        ),
    ]
