# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-20 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0029_cart_is_from_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_from_session',
        ),
    ]
