# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordertable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertableitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordertableitem',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_performer', to=settings.AUTH_USER_MODEL),
        ),
    ]
