# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertable', '0002_auto_20180227_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertableitem',
            name='main_image',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Изображение'),
        ),
    ]
