# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertable', '0003_ordertableitem_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertableitem',
            name='keywords_string',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
