# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertable', '0005_auto_20180517_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertableitem',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ordertableitem',
            name='updated',
        ),
        migrations.AddField(
            model_name='ordertableitem',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Отображать на сайте'),
        ),
    ]
