# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='users/avatars/', verbose_name='Изображение')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('bio', mezzanine.core.fields.RichTextField(default='', verbose_name='Биография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
