# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='date_of_birth',
        ),
    ]
