# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('short_description', mezzanine.core.fields.RichTextField(blank=True)),
                ('href', models.CharField(blank=True, help_text='A link to the finished project (optional)', max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Slider items',
                'verbose_name': 'Slider item',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='href',
        ),
        migrations.AddField(
            model_name='slideritem',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='theme.Slider'),
        ),
    ]
