# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20170124_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/avatars/'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='metro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
