# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20170125_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/avatars/', verbose_name='Comments'),
        ),
    ]
