# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20170209_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='short_description',
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
