# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20170125_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='metro',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/avatars/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
    ]
