# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20170209_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='slideritem',
            options={'verbose_name': 'Элемент слайдера', 'verbose_name_plural': 'Элементы слайдера'},
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='href',
            field=models.CharField(blank=True, help_text='Ссылка куда будет ввести данный слайд. Например /blog/', max_length=2000),
        ),
    ]
