# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20170210_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='href',
            field=models.CharField(blank=True, help_text='Ссылка куда будет ввести данный слайд. Например /blog/', max_length=2000, verbose_name='Ссылка'),
        ),
    ]
