# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20170210_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='google_plus',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на профиль Google+'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на профиль Twitter'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='vk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на профиль Вконтакте'),
        ),
    ]
