# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 21:34
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20170125_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='bio',
            field=mezzanine.core.fields.RichTextField(default=''),
        ),
    ]
