# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_auto_20170213_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='google_plus',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='vk',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='bio',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Расскажите о себе'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/avatars/', verbose_name='Аватарка'),
        ),
    ]
