# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-12 00:51
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_auto_20170312_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Изображение профиля'),
        ),
    ]
