# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='content',
        ),
    ]
