# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 10:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0014_remove_orderitem_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_suggest',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Пожелания к цвету'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ended',
            field=models.DateTimeField(null=True, verbose_name='Крайний срок'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='material_suggest',
            field=models.CharField(default='', max_length=500, verbose_name='Пожелания к материалам'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_suggest',
            field=models.CharField(default='', max_length=500, verbose_name='Пожелания к размерам'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
