# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0015_auto_20170528_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
