# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0023_auto_20170528_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color_suggest',
            field=models.CharField(blank=True, default='', help_text='Пример: «небесно-голубой» или «любой».', max_length=500, verbose_name='Пожелания к цвету'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='material_suggest',
            field=models.CharField(blank=True, default='', help_text='Пример: шерсть', max_length=500, verbose_name='Пожелания к материалам'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size_suggest',
            field=models.CharField(blank=True, default='', help_text='Пример: «с футбольный мяч» или «длина - 30 см».', max_length=500, verbose_name='Пожелания к размерам'),
        ),
    ]
