# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0025_auto_20170528_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Мои заказы'},
        ),
    ]
