# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('theme', '0026_auto_20170528_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работы для стола заказов',
                'ordering': ('title',),
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='work_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='orderitems', to='theme.OrderItemCategory', verbose_name='Виды работ'),
        ),
    ]
