# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-31 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0027_auto_20170529_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemcategory',
            options={'ordering': ('title',), 'verbose_name': 'Вид работы', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AddField(
            model_name='myprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_city',
            field=models.BooleanField(default=False, verbose_name='Курьером по г. Москва'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_city_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_country',
            field=models.BooleanField(default=False, verbose_name='Курьером по стране (Российская Федерация)'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_country_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_mail',
            field=models.BooleanField(default=False, verbose_name='Почта России'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_mail_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_personal',
            field=models.BooleanField(default=False, verbose_name='Личная встреча'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_personal_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_point',
            field=models.BooleanField(default=False, verbose_name='Получение в вашем пункте выдачи'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_point_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_wolrd_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='express_world',
            field=models.BooleanField(default=False, verbose_name='Курьером по миру'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='payment_bank_transfer',
            field=models.BooleanField(default=False, verbose_name='Банковский перевод'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='payment_card_transfer',
            field=models.BooleanField(default=False, verbose_name='Банковской картой'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='payment_personal',
            field=models.BooleanField(default=False, verbose_name='Наличными при получении'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='shopname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='bio',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Логотип магазина'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Если Вы не представляете, сколько подобная работа могла бы стоить, оставьте поле незаполненным.', max_digits=8, verbose_name='Бюджет'),
        ),
    ]
