# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-01 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0028_auto_20170531_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='express_wolrd_price',
            new_name='express_world_price',
        ),
    ]
