# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0029_auto_20170601_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='shopname',
            field=models.CharField(max_length=255, verbose_name='Название магазина'),
        ),
    ]
