# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-01 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0030_auto_20170601_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
    ]
