# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0031_auto_20170601_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Логотип магазина')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('bio', mezzanine.core.fields.RichTextField(default='', verbose_name='Описание')),
                ('express_point', models.BooleanField(default=False, verbose_name='Получение в вашем пункте выдачи')),
                ('express_point_price', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки')),
                ('express_city', models.BooleanField(default=False, verbose_name='Курьером по г. Москва')),
                ('express_city_price', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки')),
                ('express_country', models.BooleanField(default=False, verbose_name='Курьером по стране (Российская Федерация)')),
                ('express_country_price', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки')),
                ('express_world', models.BooleanField(default=False, verbose_name='Курьером по миру')),
                ('express_world_price', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки')),
                ('express_mail', models.BooleanField(default=False, verbose_name='Почта России')),
                ('express_mail_price', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки')),
                ('express_personal', models.BooleanField(default=False, verbose_name='Личная встреча')),
                ('express_personal_price', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, verbose_name='Цена доставки')),
                ('payment_personal', models.BooleanField(default=False, verbose_name='Наличными при получении')),
                ('payment_bank_transfer', models.BooleanField(default=False, verbose_name='Банковский перевод')),
                ('payment_card_transfer', models.BooleanField(default=False, verbose_name='Банковской картой')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_city',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_city_price',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_country',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_country_price',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_mail',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_mail_price',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_personal',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_personal_price',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_point',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_point_price',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_world',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='express_world_price',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='payment_bank_transfer',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='payment_card_transfer',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='payment_personal',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='shopname',
        ),
    ]
