# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0032_auto_20170606_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProfile',
            new_name='UserProfile',
        ),
    ]
