# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0033_auto_20170606_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='shopname',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название магазина'),
        ),
    ]
