# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0034_auto_20170606_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='usershop',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
