# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0036_auto_20170607_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='image',
            field=models.ImageField(upload_to='myprofile', verbose_name='Логотип магазина'),
        ),
    ]
