# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0038_auto_20170607_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='express_city_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_country_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_mail_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_personal_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_point_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_world_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
    ]
