# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0043_auto_20170607_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='background',
            field=models.ImageField(blank=True, default='', upload_to='tmp_images/', verbose_name='Обложка магазина'),
        ),
    ]
