# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0044_usershop_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='bio',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Расскажите интересные факты о создании своего бренда, опишите его особенности и преимущества. Перечислите свои флагманские вещи, расскажите кратко про производство, материалы. Напишите как минимум три предложения о себе. Главная страница магазина будет выглядеть красивее, а мы это учитываем, когда отбираем магазины в раздел «Лучшее» и в редакционные подборки.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='country',
            field=models.CharField(default='', max_length=255, verbose_name='Страна'),
        ),
    ]
