# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0045_auto_20170609_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='express_other',
            field=models.CharField(blank=True, help_text='Опишите любые другие условия и важные моменты по оплате — покупателю будет проще принять решение о покупке в вашем магазине.', max_length=255, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_city_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='', help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_country_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='', help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_mail_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='', help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_personal_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='', help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_point_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='', help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_world_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='', help_text='Оставляйте поле пустым, если стоимость будет рассчитана по запросу.', max_digits=8, null=True, verbose_name='Цена доставки'),
        ),
    ]
