# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0047_auto_20170609_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='background',
            field=models.ImageField(default='', upload_to='tmp_images/', verbose_name='Обложка магазина'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='image',
            field=models.ImageField(default='', upload_to='tmp_images/', verbose_name='Логотип магазина'),
        ),
    ]
