# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-11 11:09
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0048_auto_20170610_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='rules',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Обозначьте условия возврата товаров. В течение какого времени после получения товара покупатель может обратиться? Если вы не принимаете возвраты или обмены, чётко укажите на это, чтобы избежать споров в случае желания покупателя отказаться от покупки.', verbose_name='Дополнительная информация об оплате'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='express_other',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Адреса, по которым покупатель сможет забрать товар самостоятельно. Любые другие нюансы и условия по доставке.', verbose_name='Дополнительная информация о доставке'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='payment_other',
            field=mezzanine.core.fields.RichTextField(default='', help_text='Опишите любые другие условия и важные моменты по оплате — покупателю будет проще принять решение о покупке в вашем магазине.', verbose_name='Дополнительная информация об оплате'),
        ),
    ]
