# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0047_auto_20170609_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershop',
            name='city',
        ),
        migrations.AddField(
            model_name='usershop',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='Город'),
        ),
        migrations.RemoveField(
            model_name='usershop',
            name='country',
        ),
        migrations.AddField(
            model_name='usershop',
            name='country',
            field=models.CharField(default='', max_length=255, verbose_name='Страна'),
        ),
    ]
