# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0045_auto_20170609_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
    ]
